"""initial planner schema

Revision ID: 99d9ec79ab7e
Revises:
Create Date: 2026-09-02 17:16:04.353873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '99d9ec79ab7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarevent',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.Enum('HARD', 'SOFT', 'PROTECTED', 'FLOATING', name='blockkind'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarevent_end_at'), 'calendarevent', ['end_at'], unique=False)
    op.create_index(op.f('ix_calendarevent_kind'), 'calendarevent', ['kind'], unique=False)
    op.create_index(op.f('ix_calendarevent_start_at'), 'calendarevent', ['start_at'], unique=False)
    op.create_table('course',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_code'), 'course', ['code'], unique=True)
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providerconfiguration',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('credential_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providerconfiguration_provider'), 'providerconfiguration', ['provider'], unique=False)
    op.create_table('schedulerun',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocks_created', sa.Integer(), nullable=False),
    sa.Column('unscheduled_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syncrun',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpreferences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_start_hour', sa.Integer(), nullable=False),
    sa.Column('day_end_hour', sa.Integer(), nullable=False),
    sa.Column('preferred_start_hour', sa.Integer(), nullable=False),
    sa.Column('min_block_minutes', sa.Integer(), nullable=False),
    sa.Column('max_block_minutes', sa.Integer(), nullable=False),
    sa.Column('safety_buffer_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('DETECTED', 'ANALYZED', 'AWAITING_CALIBRATION', 'CALIBRATION_IN_PROGRESS', 'CALIBRATED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'STALE', 'ERROR', name='assignmentstate'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('base_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('proficiency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('assignment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_course_id'), 'assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignment_due_at'), 'assignment', ['due_at'], unique=False)
    op.create_index(op.f('ix_assignment_state'), 'assignment', ['state'], unique=False)
    op.create_table('modelroute',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_configuration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_configuration_id'], ['providerconfiguration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelroute_task'), 'modelroute', ['task'], unique=True)
    op.create_table('topic',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_topic_key'), 'topic', ['topic_key'], unique=True)
    op.create_table('assignmentanalysis',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('estimated_difficulty', sa.Float(), nullable=False),
    sa.Column('base_time_minutes', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('assignment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignmentanalysis_assignment_id'), 'assignmentanalysis', ['assignment_id'], unique=False)
    op.create_table('assignmentsnapshot',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignmentsnapshot_assignment_id'), 'assignmentsnapshot', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignmentsnapshot_content_hash'), 'assignmentsnapshot', ['content_hash'], unique=False)
    op.create_table('calibration',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('mastery_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_assignment_id'), 'calibration', ['assignment_id'], unique=False)
    op.create_table('historicalworkrecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masteryrecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('recent_error_types', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masteryrecord_topic_id'), 'masteryrecord', ['topic_id'], unique=False)
    op.create_table('scheduledecision',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_run_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedulerun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studyblock',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.Enum('HARD', 'SOFT', 'PROTECTED', 'FLOATING', name='blockkind'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('schedule_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedulerun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studyblock_assignment_id'), 'studyblock', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_studyblock_end_at'), 'studyblock', ['end_at'], unique=False)
    op.create_index(op.f('ix_studyblock_start_at'), 'studyblock', ['start_at'], unique=False)
    op.create_table('calibrationquestion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_topics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrationquestion_calibration_id'), 'calibrationquestion', ['calibration_id'], unique=False)
    op.create_table('calibrationanswer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['calibrationquestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrationanswer_question_id'), 'calibrationanswer', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibrationanswer_question_id'), table_name='calibrationanswer')
    op.drop_table('calibrationanswer')
    op.drop_index(op.f('ix_calibrationquestion_calibration_id'), table_name='calibrationquestion')
    op.drop_table('calibrationquestion')
    op.drop_index(op.f('ix_studyblock_start_at'), table_name='studyblock')
    op.drop_index(op.f('ix_studyblock_end_at'), table_name='studyblock')
    op.drop_index(op.f('ix_studyblock_assignment_id'), table_name='studyblock')
    op.drop_table('studyblock')
    op.drop_table('scheduledecision')
    op.drop_index(op.f('ix_masteryrecord_topic_id'), table_name='masteryrecord')
    op.drop_table('masteryrecord')
    op.drop_table('historicalworkrecord')
    op.drop_index(op.f('ix_calibration_assignment_id'), table_name='calibration')
    op.drop_table('calibration')
    op.drop_index(op.f('ix_assignmentsnapshot_content_hash'), table_name='assignmentsnapshot')
    op.drop_index(op.f('ix_assignmentsnapshot_assignment_id'), table_name='assignmentsnapshot')
    op.drop_table('assignmentsnapshot')
    op.drop_index(op.f('ix_assignmentanalysis_assignment_id'), table_name='assignmentanalysis')
    op.drop_table('assignmentanalysis')
    op.drop_index(op.f('ix_topic_topic_key'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_modelroute_task'), table_name='modelroute')
    op.drop_table('modelroute')
    op.drop_index(op.f('ix_assignment_state'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_due_at'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_course_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_table('userpreferences')
    op.drop_table('syncrun')
    op.drop_table('schedulerun')
    op.drop_index(op.f('ix_providerconfiguration_provider'), table_name='providerconfiguration')
    op.drop_table('providerconfiguration')
    op.drop_table('notification')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_index(op.f('ix_course_code'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_calendarevent_start_at'), table_name='calendarevent')
    op.drop_index(op.f('ix_calendarevent_kind'), table_name='calendarevent')
    op.drop_index(op.f('ix_calendarevent_end_at'), table_name='calendarevent')
    op.drop_table('calendarevent')
    # ### end Alembic commands ###
