"""academic os canvas and event core

Revision ID: a58abab3fe5f
Revises: 99d9ec79ab7e
Create Date: 2026-09-02 19:22:17.508667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a58abab3fe5f'
down_revision: Union[str, None] = '99d9ec79ab7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgroundjob',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backgroundjob_job_key'), 'backgroundjob', ['job_key'], unique=True)
    op.create_index(op.f('ix_backgroundjob_job_type'), 'backgroundjob', ['job_type'], unique=False)
    op.create_index(op.f('ix_backgroundjob_scheduled_at'), 'backgroundjob', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_backgroundjob_status'), 'backgroundjob', ['status'], unique=False)
    op.create_table('canvasworkerstate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('courses_observed', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scan_in_progress', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domainevent',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domainevent_correlation_id'), 'domainevent', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_domainevent_entity_id'), 'domainevent', ['entity_id'], unique=False)
    op.create_index(op.f('ix_domainevent_entity_type'), 'domainevent', ['entity_type'], unique=False)
    op.create_index(op.f('ix_domainevent_event_type'), 'domainevent', ['event_type'], unique=False)
    op.create_table('modelusagerecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('approximate_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelusagerecord_model'), 'modelusagerecord', ['model'], unique=False)
    op.create_index(op.f('ix_modelusagerecord_provider'), 'modelusagerecord', ['provider'], unique=False)
    op.create_index(op.f('ix_modelusagerecord_task'), 'modelusagerecord', ['task'], unique=False)
    op.create_table('academicdocument',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academicdocument_content_hash'), 'academicdocument', ['content_hash'], unique=False)
    op.create_index(op.f('ix_academicdocument_course_id'), 'academicdocument', ['course_id'], unique=False)
    op.create_table('announcement',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(), nullable=False),
    sa.Column('relevant_dates', sa.JSON(), nullable=True),
    sa.Column('affects_planning', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_canonical_url'), 'announcement', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_announcement_course_id'), 'announcement', ['course_id'], unique=False)
    op.create_table('exam',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('exam_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coverage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('preparation_start_at', sa.DateTime(), nullable=True),
    sa.Column('format_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_course_id'), 'exam', ['course_id'], unique=False)
    op.create_index(op.f('ix_exam_source_url'), 'exam', ['source_url'], unique=False)
    op.create_index(op.f('ix_exam_start_at'), 'exam', ['start_at'], unique=False)
    op.create_table('studysession',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_block_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('completion_fraction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['study_block_id'], ['studyblock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studysession_study_block_id'), 'studysession', ['study_block_id'], unique=False)
    op.add_column('assignment', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('source_lms', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='local'))
    op.add_column('assignment', sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('points_possible', sa.Float(), nullable=True))
    op.add_column('assignment', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('assignment', sa.Column('lock_at', sa.DateTime(), nullable=True))
    op.add_column('assignment', sa.Column('first_observed_at', sa.DateTime(), nullable=True))
    op.add_column('assignment', sa.Column('last_observed_at', sa.DateTime(), nullable=True))
    op.add_column('assignment', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('raw_metadata', sa.JSON(), nullable=True))
    op.add_column('assignment', sa.Column('extracted_topics', sa.JSON(), nullable=True))
    op.add_column('assignment', sa.Column('inferred_difficulty', sa.Float(), nullable=True))
    op.add_column('assignment', sa.Column('actual_minutes', sa.Integer(), nullable=True))
    op.add_column('assignment', sa.Column('duration_override_minutes', sa.Integer(), nullable=True))
    op.add_column('assignment', sa.Column('completion_override', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_assignment_canonical_url'), 'assignment', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_assignment_content_hash'), 'assignment', ['content_hash'], unique=False)
    op.create_index(op.f('ix_assignment_external_id'), 'assignment', ['external_id'], unique=False)
    op.add_column('course', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Rutgers University'))
    op.add_column('course', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('instructor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('canvas_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='ACTIVE'))
    op.add_column('course', sa.Column('first_observed_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('last_observed_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('course', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_course_canvas_url'), 'course', ['canvas_url'], unique=False)
    op.create_index(op.f('ix_course_external_id'), 'course', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_external_id'), table_name='course')
    op.drop_index(op.f('ix_course_canvas_url'), table_name='course')
    op.drop_column('course', 'metadata_json')
    op.drop_column('course', 'archived')
    op.drop_column('course', 'last_observed_at')
    op.drop_column('course', 'first_observed_at')
    op.drop_column('course', 'status')
    op.drop_column('course', 'canvas_url')
    op.drop_column('course', 'instructor')
    op.drop_column('course', 'section')
    op.drop_column('course', 'department')
    op.drop_column('course', 'institution')
    op.drop_column('course', 'term')
    op.drop_column('course', 'external_id')
    op.drop_index(op.f('ix_assignment_external_id'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_content_hash'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_canonical_url'), table_name='assignment')
    op.drop_column('assignment', 'completion_override')
    op.drop_column('assignment', 'duration_override_minutes')
    op.drop_column('assignment', 'actual_minutes')
    op.drop_column('assignment', 'inferred_difficulty')
    op.drop_column('assignment', 'extracted_topics')
    op.drop_column('assignment', 'raw_metadata')
    op.drop_column('assignment', 'content_hash')
    op.drop_column('assignment', 'last_observed_at')
    op.drop_column('assignment', 'first_observed_at')
    op.drop_column('assignment', 'lock_at')
    op.drop_column('assignment', 'available_from')
    op.drop_column('assignment', 'points_possible')
    op.drop_column('assignment', 'canonical_url')
    op.drop_column('assignment', 'source_lms')
    op.drop_column('assignment', 'external_id')
    op.drop_index(op.f('ix_studysession_study_block_id'), table_name='studysession')
    op.drop_table('studysession')
    op.drop_index(op.f('ix_exam_start_at'), table_name='exam')
    op.drop_index(op.f('ix_exam_source_url'), table_name='exam')
    op.drop_index(op.f('ix_exam_course_id'), table_name='exam')
    op.drop_table('exam')
    op.drop_index(op.f('ix_announcement_course_id'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_canonical_url'), table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_academicdocument_course_id'), table_name='academicdocument')
    op.drop_index(op.f('ix_academicdocument_content_hash'), table_name='academicdocument')
    op.drop_table('academicdocument')
    op.drop_index(op.f('ix_modelusagerecord_task'), table_name='modelusagerecord')
    op.drop_index(op.f('ix_modelusagerecord_provider'), table_name='modelusagerecord')
    op.drop_index(op.f('ix_modelusagerecord_model'), table_name='modelusagerecord')
    op.drop_table('modelusagerecord')
    op.drop_index(op.f('ix_domainevent_event_type'), table_name='domainevent')
    op.drop_index(op.f('ix_domainevent_entity_type'), table_name='domainevent')
    op.drop_index(op.f('ix_domainevent_entity_id'), table_name='domainevent')
    op.drop_index(op.f('ix_domainevent_correlation_id'), table_name='domainevent')
    op.drop_table('domainevent')
    op.drop_table('canvasworkerstate')
    op.drop_index(op.f('ix_backgroundjob_status'), table_name='backgroundjob')
    op.drop_index(op.f('ix_backgroundjob_scheduled_at'), table_name='backgroundjob')
    op.drop_index(op.f('ix_backgroundjob_job_type'), table_name='backgroundjob')
    op.drop_index(op.f('ix_backgroundjob_job_key'), table_name='backgroundjob')
    op.drop_table('backgroundjob')
    # ### end Alembic commands ###
