from enum import Enum


class ModelTask(str, Enum):
    CANVAS_COMPUTER_USE = "CANVAS_COMPUTER_USE"
    COURSE_RESEARCH = "COURSE_RESEARCH"
    TOPIC_CLASSIFICATION = "TOPIC_CLASSIFICATION"
    MICRO_QUIZ_GENERATION = "MICRO_QUIZ_GENERATION"
    QUIZ_GRADING = "QUIZ_GRADING"
    DIAGNOSTIC_GENERATION = "DIAGNOSTIC_GENERATION"
    MASTERY_UPDATE = "MASTERY_UPDATE"
    DURATION_ESTIMATION = "DURATION_ESTIMATION"
    SCHEDULE_STRATEGY = "SCHEDULE_STRATEGY"
    EXAM_PLAN = "EXAM_PLAN"
    TUTORING = "TUTORING"
